---
# Copyright (c) Richard Gee 2018. All rights reserved.
# Licensed under the MIT license. See LICENSE file in the project root for full license information.
- hosts: localhost
  connection: local
  roles:
    - create_droplet
  
- hosts: "{{ hostvars.localhost.droplet_ip }}"
  remote_user: root
  gather_facts: false
  pre_tasks:
  - name: Install Python
    raw: sudo apt-get -y install python-simplejson
  - name: Import SSL
    raw: python -c "import ssl"

  roles: 
   - docker
   - { role: configure_swarm, when: orchestrator == 'swarm' }
   - { role: install_k8s, when: orchestrator == 'k8s'}
   - { role: configure_k8s, when: orchestrator == 'k8s'}
   - { role: helm, when: orchestrator == 'k8s'}
   - { role: openfaas_k8s, when: orchestrator == 'k8s'}
   - { role: openfaas_swarm, when: orchestrator == 'swarm'}
   - output
